routes/endpoints.py
from database import db
from flask import Blueprint
from flask import Flask, render_template, jsonify, request, redirect, url_for, flash
from models import Users, Collection, PokeCollection, Pokemon
from flask_login import login_user, logout_user, current_user
import requests
import string

from pokedex import pokedex

import os
web_pages_bp = Blueprint("html", __name__)


@web_pages_bp.route("/")
def base():
    return render_template("home.html", current_page="nogen")


@web_pages_bp.route("/home")
def home():
    return render_template("home.html", current_page="nogen")


@web_pages_bp.route("/gen<int:number>")
def gen(number):
    amounts = [151, 100, 135, 107, 156, 72, 88, 96, 120]
    startNumber = [1, 152, 252, 387, 494, 650, 722, 810, 906]
    return render_template("generations.html", number=number, pokedex=pokedex, amounts=amounts, startNumber=startNumber)


@web_pages_bp.route("/register")
def register():
    return render_template("register.html", current_page="nogen")


@web_pages_bp.route("/login")
def login():
    return render_template("login.html", current_page="nogen")


@web_pages_bp.route("/logout")
def logout():
    logout_user()
    return render_template("home.html", current_page="nogen")


@web_pages_bp.route("/add", methods=["POST"])
def add_pokemon():

    if not current_user.is_authenticated:
        flash("You are not logged in.")
        return redirect(url_for('html.login'))

    number = request.form.get("pokemon_number")
    gen_number = request.form.get("gen_number")

    collection = Collection.query.filter_by(user_id=current_user.id).first()
    if not collection:
        collection = Collection(user_id=current_user.id)
        db.session.add(collection)
        db.session.commit()

    exist = db.session.execute(db.select(PokeCollection).where(
        PokeCollection.collection_id == collection.id,
        PokeCollection.pokemon_number == number
    )).first()
    if exist:
        return redirect(url_for('html.gen', number=gen_number))

    pokemon = db.select(Pokemon).where(Pokemon.number == number)
    addPokemon = db.session.execute(pokemon).scalar()
    if addPokemon == None:
        pokemon = Pokemon(number=number)
        db.session.add(pokemon)

    pokecollection = PokeCollection(
        collection_id=collection.id, pokemon_number=number)
    db.session.add(pokecollection)

    db.session.commit()

    return redirect(url_for('html.gen', number=gen_number))


@web_pages_bp.route("/remove", methods=["POST"])
def remove_pokemon():
    if not current_user.is_authenticated:
        flash("You are not logged in.")
        return redirect(url_for('html.login'))

    number = request.form.get("pokemon_number")

    collection = Collection.query.filter_by(user_id=current_user.id).first()

    exist = db.session.execute(db.select(PokeCollection).where(
        PokeCollection.collection_id == collection.id,
        PokeCollection.pokemon_number == number
    )).scalar()

    if exist:
        db.session.delete(exist)
        db.session.commit()
    return redirect(url_for('api_collections.get_collection'))


@web_pages_bp.route("/info<int:number>",)
def info(number):
    response = requests.get(f"https://pokeapi.co/api/v2/pokemon/{number}/")
    data = response.json()

    weight = data['weight']
    height = data['height']

    hp = None
    defense = None
    attack = None
    special_attack = None
    special_defense = None
    speed = None

    for stat in data['stats']:
        if stat['stat']['name'] == 'hp':
            hp = stat['base_stat']
        if stat['stat']['name'] == 'defense':
            defense = stat['base_stat']
        if stat['stat']['name'] == 'attack':
            attack = stat['base_stat']
        if stat['stat']['name'] == 'special-attack':
            special_attack = stat['base_stat']
        if stat['stat']['name'] == 'special-defense':
            special_defense = stat['base_stat']
        if stat['stat']['name'] == 'speed':
            speed = stat['base_stat']

    # moves = []

    # for move in data['moves']:
    #     move_name = move["move"]["name"]
    #     for version_detail in move["version_group_details"]:
    #         version_name = version_detail["version_group"]["name"]
    #         moves.append(
    #             {"name": move_name, "version": version_name})

    response = requests.get(
        f"https://pokeapi.co/api/v2/pokemon/{number}/encounters")
    data = response.json()
    
    versions_with_locations = {}

    for location in data:
        location_name = location["location_area"]["name"]
        location_name = location_name.replace("-", " ")
        location_name = string.capwords(location_name)
        
        for version_detail in location["version_details"]:
            version_name = version_detail["version"]["name"]
            version_name = version_name.replace("-", " ")
            version_name = string.capwords(version_name)
            
            if version_name not in versions_with_locations:
                versions_with_locations[version_name] = []
            
            versions_with_locations[version_name].append(location_name)

    return render_template("info.html",
                           pokedex=pokedex,
                           number=number,
                           weight=weight, height=height,
                           hp=hp, defense=defense,
                           attack=attack,
                           special_attack=special_attack,
                           special_defense=special_defense,
                           speed=speed,
                           versions_with_locations=versions_with_locations,
                        #    moves=moves
                           )

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- <link rel="stylesheet" href="static/style.css"> -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
      rel="stylesheet"
    />
    <link rel="icon" href="/static/assests/pokeball-pokemon-svgrepo-com.svg">
  </head>

  <body>
    <div class="sidebar">
      <button type="button" class="btn btn-primary link-light">
        <a href="{{ url_for('html.home') }}" class="link-light">
          <img
            class="sidebarphoto"
            src="/static/assests/navbar/home.svg"
            title="Home"
        /></a>
      </button>
      <button type="button" class="btn btn-primary">
        <a href="{{ url_for('html.register') }}" class="link-light">
          <img
            class="sidebarphoto"
            src="/static/assests/navbar/register.svg"
            title="Register"
        /></a>
      </button>
      <button type="button" class="btn btn-primary">
        <a href="{{ url_for('html.login') }}" class="link-light">
          <img
            class="sidebarphoto"
            src="/static/assests/navbar/login.svg"
            title="Login"
          />
        </a>
      </button>
      <button type="button" class="btn btn-primary">
        <a href="{{ url_for('html.logout') }}" class="link-light">
          <img
            class="sidebarphoto"
            src="/static/assests/navbar/logout.svg"
            title="Logout"
        /></a>
      </button>
      <button type="button" class="btn btn-primary">
        <a
          href="{{ url_for('api_collections.get_collection') }}"
          class="link-light"
        >
          <img
            class="sidebarphoto"
            src="/static/assests/navbar/collection.svg"
            title="Collections"
        /></a>
      </button>
    </div>
    {% if current_page != 'nogen'%}
    <section class="section">
      <div class="genbarbase">
        <div class="tab-navigation">
            <ul class="tab-menu-home">
                        <li class="item-list"><a href="{{ url_for('html.gen', number='1') }}" class="genHome">Gen 1
                            <!-- <button type="button" class="btn btn-primary genHome">Gen 1</button> -->
                        </a></li>
                <li class="item-list">
                    <!-- <button type="button" class="btn btn-primary genHome"> -->
                        <a href="{{ url_for('html.gen', number='2') }}" class="genHome">Gen 2</a>
                    </button>
                </li>
                <li class="item-list">
                    <!-- <button type="button" class="btn btn-primary genHome"> -->
                        <a href="{{ url_for('html.gen', number='3') }}" class="genHome">Gen 3</a>
                    </button>
                </li>
                <li class="item-list">
                    <!-- <button type="button" class="btn btn-primary genHome"> -->
                        <a href="{{ url_for('html.gen', number='4') }}" class="genHome">Gen 4</a>
                    </button>
                </li>
                <li class="item-list">
                    <!-- <button type="button" class="btn btn-primary genHome"> -->
                        <a href="{{ url_for('html.gen', number='5') }}" class="genHome">Gen 5</a>
                    </button>
                </li>
                <li class="item-list">
                    <!-- <button type="button" class="btn btn-primary genHome"> -->
                        <a href="{{ url_for('html.gen', number='6') }}" class="genHome">Gen 6</a>
                    </button>
                </li>
                <li class="item-list">
                    <!-- <button type="button" class="btn btn-primary genHome"> -->
                        <a href="{{ url_for('html.gen', number='7') }}" class="genHome">Gen 7</a>
                    </button>
                </li>
                <li class="item-list">
                    <!-- <button type="button" class="btn btn-primary genHome"> -->
                        <a href="{{ url_for('html.gen', number='8') }}" class="genHome">Gen 8</a>
                    </button>
                </li>
                <li class="item-list">
                    <!-- <button type="button" cl   ass="btn btn-primary genHome"> -->
                        <a href="{{ url_for('html.gen', number='9') }}" class="genHome">Gen 9</a>
                    </button>
        </div>
    </div>
    </div>
    </section>
    {%endif%} {% block content %} {% endblock %}
  </body>
</html>

templates/collections.html
{% extends "base.html" %} {% block content %}
<div id="filterbtns" class="filbtn">
  <ul>
    <li><button type="button" class="filter btn" onclick="showAll()">All</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Grass')">Grass</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Fire')">Fire</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Water')">Water</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Bug')">Bug</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Poison')">Poison</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Flying')">Flying</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Normal')">Normal</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Electric')">Electric</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Ground')">Ground</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Fairy')">Fairy</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Psychic')">Psychic</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Ghost')">Ghost</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Ice')">Ice</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Dragon')">Dragon</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Dark')">Dark</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Fighting')">Fighting</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Rock')">Rock</button></li>
    <li><button type="button" class="filter btn" onclick="showPokemon('Steel')">Steel</button></li>
  </ul>
</div>

<div id="searchbar">
  <input type="text" id="SearchInput" onkeyup="searchfunc()" placeholder="Search">
</div>

<div class="header-gen">
  <h1 class="missingH1">The Pokémon you are missing are:</h1>
</div>

<div class="pokePage">
  {% for i in pokemon %}
  <div class="pokeDiv">
    <div class="{{i.pokemon_number}}"></div>
    <h2>{{pokedex[i.pokemon_number].name }} #{{i.pokemon_number}}</h2>
    <img
      class="pokeImage"
      src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/{{i.pokemon_number}}.png"
    />
    <div class="power-wrapper">
      {% set types = pokedex[i.pokemon_number].type %}
        {% for type in types %}
          <p class="power-wrapper {{type}}">{{ type }}</p>
        {% endfor %}
    </div>

    {% for type in types %}
      <div class="{{ type }}" style="display: none;"></div>
    {% endfor %}

  <div class="padding">
    <form method="POST" action="{{ url_for('html.remove_pokemon') }}">
      <input type="hidden" name="pokemon_number" value="{{ i.pokemon_number }}"/>
      <button type="submit" class="infobutton addCollection">
        Remove
      </button>
    </form>
  </div>
    <button class="infobutton outsideInfoButton">
      <a class="infobutton" href="{{ url_for('html.info', number=i.pokemon_number) }}">Information</a>
    </button>
  </div>
  {% endfor %}
</div>

<script>
  function searchfunc(){
    const pokePage = document.querySelector('.pokePage')

    if (!pokePage) {
      console.log('No pokePage container found.');
      return;
    }

    const input = document.getElementById('SearchInput');
    const filter = input.value.toUpperCase();
    const pokeDivs = pokePage.querySelectorAll('.pokeDiv');

    pokeDivs.forEach((pokeDiv, index) => {
      const h2 = pokeDiv.querySelector('h2');
      if (h2) {
        const txtValue = h2.textContent || h2.innerText;

        if (txtValue.toUpperCase().includes(filter)) {
          pokeDiv.classList.remove('hidden');
        } else{
          pokeDiv.classList.add('hidden');
        }
      }

    });
  }
  //var typedic = {
  //}
  function showPokemon(type) {
    document.querySelectorAll('.pokeDiv').forEach(function(element) {
      element.classList.add('hidden');
    });
    //for (var typeKey in typedic) {
    //  typedic[typeKey] = false;
    //}
    document.querySelectorAll('.' + type).forEach(function(element) {
      element.parentElement.classList.remove('hidden');
      //typedic[type] = true;
    });
  }

  function showAll() {
    document.querySelectorAll('.pokeDiv').forEach(function(element) {
      element.classList.remove('hidden');
    });
  }
</script>

{% endblock %}

templates/generations.html
{% extends "base.html" %} {% block content %}
<section class="genSection">
  
  <div id="searchbar">
    <input type="text" id="SearchInput" onkeyup="searchfunc()" placeholder="Search">
  </div>

  <div class="header-gen">
    <div class="gen-textbox">
      <h1>Generation {{ number }}</h1>
    </div>
  </div>
  
  <div id="filterbtns" class="filbtn">
    <ul>
      <li><button type="button" class="filter btn" onclick="showAll()">All</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Grass')">Grass</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Fire')">Fire</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Water')">Water</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Bug')">Bug</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Poison')">Poison</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Flying')">Flying</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Normal')">Normal</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Electric')">Electric</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Ground')">Ground</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Fairy')">Fairy</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Psychic')">Psychic</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Ghost')">Ghost</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Ice')">Ice</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Dragon')">Dragon</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Dark')">Dark</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Fighting')">Fighting</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Rock')">Rock</button></li>
      <li><button type="button" class="filter btn" onclick="showPokemon('Steel')">Steel</button></li>
    </ul>
  </div>
  
  <div class="pokePage">
    {% for i in range((startNumber[number - 1]), (startNumber[number - 1] +
    amounts[number - 1])) %}
    <div class="pokeDiv">
      <div class="{{i}}"></div>
      <!-- <h1>{{i}}</h1> -->
      <h2>{{pokedex[i].name}} #{{i}}</h2>
      <img
        class="pokeImage"
        src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/{{i}}.png"
      />
      
      <div class="power-wrapper">
        {% set types = pokedex[i].type %}
          {% for type in types %}
            <p class="power-wrapper {{type}}">{{ type }}</p>
          {% endfor %}
      </div>

      {% for type in types %}
        <div class="{{ type }}" style="display: none;"></div>
      {% endfor %}

      <div class="padding">
        <form method="POST" action="{{ url_for('html.add_pokemon') }}">
          <input type="hidden" name="pokemon_number" value="{{ i }}" />
          <input type="hidden" name="gen_number" value="{{ number }}" />
          <button type="submit" class="infobutton addCollection">
            Add to Collection
          </button>

        </form>
      </div>
      <button class="infobutton outsideInfoButton">
        <a class="infobutton" href="{{ url_for('html.info', number=i) }}">Information</a>
      </button>
    </div>
    {% endfor %}
  </div>
  
  <script>
    function searchfunc(){
      const pokePage = document.querySelector('.pokePage')

      if (!pokePage) {
        console.log('No pokePage container found.');
        return;
      }

      const input = document.getElementById('SearchInput');
      const filter = input.value.toUpperCase();
      const pokeDivs = pokePage.querySelectorAll('.pokeDiv');

      pokeDivs.forEach((pokeDiv, index) => {
        const h2 = pokeDiv.querySelector('h2');
        if (h2) {
          const txtValue = h2.textContent || h2.innerText;

          if (txtValue.toUpperCase().includes(filter)) {
            pokeDiv.classList.remove('hidden');
          } else{
            pokeDiv.classList.add('hidden');
          }
        }

      });
    }
    //var typedic = {
    //}
    function showPokemon(type) {
      document.querySelectorAll('.pokeDiv').forEach(function(element) {
        element.classList.add('hidden');
      });
      //for (var typeKey in typedic) {
      //  typedic[typeKey] = false;
      //}
      document.querySelectorAll('.' + type).forEach(function(element) {
        element.parentElement.classList.remove('hidden');
        //typedic[type] = true;
      });
    }

    function showAll() {
      document.querySelectorAll('.pokeDiv').forEach(function(element) {
        element.classList.remove('hidden');
      });
    }
  </script>
  

  {% endblock %}
</section>

templates/home.html
{% extends "base.html" %} {% block content %}
<img class="homePage" src="/static/assests/homePage.jpg" alt="" />
<div class="content-wrapper">
  {% with messages = get_flashed_messages() %} {% if messages %} {% for message
  in messages %}
  <script>
    let message = "{{ message }}";
    alert(message);
  </script>
  {% endfor %} {% endif %} {% endwith %}
  <section class="header">
    <div class="content-home">
      <div class="input-text-home">
        <div class="textbox">
          <div class="logo">
            <img
              class="pokeball"
              src="/static/assests/pokeball-pokemon-svgrepo-com.svg"
              alt="Pokeball Logo"
            />
            <h1>Poké Tracker</h1>
          </div>
          <!-- Container for the buttons -->
          <div class="button-container">
            <a href="{{ url_for('html.register') }}" class="register-hover">
              <button type="button" class="homebutton">Register</button>
            </a>
            <a href="{{ url_for('html.login') }}" class="login-hover">
              <button type="button" class="homebutton">Login</button>
            </a>
          </div>
        </div>

        <div class="genbarhome">
          <div class="tab-navigation">
            <ul class="tab-menu-home">
              <li class="item-list">
                <a href="{{ url_for('html.gen', number='1') }}" class="genHome"
                  >Gen 1</a
                >
              </li>
              <li class="item-list">
                <a href="{{ url_for('html.gen', number='2') }}" class="genHome"
                  >Gen 2</a
                >
              </li>
              <li class="item-list">
                <a href="{{ url_for('html.gen', number='3') }}" class="genHome"
                  >Gen 3</a
                >
              </li>
              <li class="item-list">
                <a href="{{ url_for('html.gen', number='4') }}" class="genHome"
                  >Gen 4</a
                >
              </li>
              <li class="item-list">
                <a href="{{ url_for('html.gen', number='5') }}" class="genHome"
                  >Gen 5</a
                >
              </li>
              <li class="item-list">
                <a href="{{ url_for('html.gen', number='6') }}" class="genHome"
                  >Gen 6</a
                >
              </li>
              <li class="item-list">
                <a href="{{ url_for('html.gen', number='7') }}" class="genHome"
                  >Gen 7</a
                >
              </li>
              <li class="item-list">
                <a href="{{ url_for('html.gen', number='8') }}" class="genHome"
                  >Gen 8</a
                >
              </li>
              <li class="item-list">
                <a href="{{ url_for('html.gen', number='9') }}" class="genHome"
                  >Gen 9</a
                >
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %} {% block content %} {% with messages =
get_flashed_messages() %} {% if messages %} {% for message in messages %}
<script>
  let message = "{{ message }}";
  alert(message);
</script>
{% endfor %} {% endif %} {% endwith %}
<div class="all">
  <div class="body-login">
    <div class="content">
      <form action="#" method="POST">
        <h2>Login:</h2>
        <div class="input-box">
          <label for="username">Username:</label>
          <input type="text" name="username"/>
        </div>

        <div class="input-box">
          <label for="password">Password:</label>
          <input type="password" name="password" />
          <button type="submit" class="login-btn">Login</button>
        </div>
      </form>
      <p class="loginP">Don't have an account?</p>
      <a href="{{ url_for('html.register') }}" class="reg-login">
        <button type="button" class="login-reg-btn">Register</button>
      </a>
    </div>
  </div>
</div>

{% endblock %}

templates/notlog.html
{% extends "base.html" %}

{% block content %}

<h1>You are not logged in!</h1>
<p>To keep track of your missing pokemon:</p>
<h1>Login:</h1>
<form action="#" method="POST">
    <label for="username">Username:</label>
    <input type="text" name="username"/>
    <label for="password">Password:</label>
    <input type="password" name="password"/>
    <button type="submit">Submit</button>
</form>
<p>or</p>
<h1>Register:</h1>
<form action="#" method="POST">
    <label for="username">Username:</label>
    <input type="text" name="username"/>
    <label for="password">Password:</label>
    <input type="password" name="password"/>
    <button type="submit">Submit</button>
</form>
{% endblock %}

templates/register.html
{% extends "base.html" %} {% block content %} {% with messages =
get_flashed_messages() %} {% if messages %} {% for message in messages %}
<script>
  let message = "{{ message }}";
  alert(message);
</script>
{% endfor %} {% endif %} {% endwith %}

<div class="all">
  <div class="body-login1">
    <div class="content">
      <form action="#" method="POST">
        <h2>Register:</h2>
        <div class="input-box">
          <label for="username">Username:</label>
          <input type="text" name="username" />
        </div>

        <div class="input-box">
          <label for="password">Password:</label>
          <input type="password" name="password" />
          <button type="submit" class="login-btn">Submit</button>
        </div>
      </form>
      <p class="loginP">Already have an account?</p>
      <a href="{{ url_for('html.login') }}" class="reg-login">
        <button type="button" class="login-reg-btn">Login</button>
      </a>
    </div>
  </div>
</div>

{% endblock %}